/*
Statement:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

/*
Logic:

Adding the two previous number to give current term is Fibonacci series.
Only even terms are added to the total sum until current Fib term exceeds the limit
of 4 million.

*/


#include<iostream>
using namespace std;

int main()
{
    unsigned int evenSum = 0, limit = 4000000;

    int f = 1, s = 2, cur = 2;

    while(true)
    {
        if(cur>limit) break;

        if(! (cur&1) )
            evenSum += cur;

        cur = f+s;
        f = s;
        s = cur;
    }

    cout<<evenSum<<endl;

    return 0;
}